import React, { createContext, useState, useEffect } from "react";

export const LANGUAGES = [
  { code: "mn", label: "Монгол", flag: "🇲🇳", dir: "ltr" },
  { code: "en", label: "English", flag: "🇬🇧", dir: "ltr" },
  { code: "de", label: "Deutsch", flag: "🇩🇪", dir: "ltr" },
  { code: "ko", label: "한국어", flag: "🇰🇷", dir: "ltr" },
  { code: "ja", label: "日本語", flag: "🇯🇵", dir: "ltr" },
  { code: "zh", label: "中文", flag: "🇨🇳", dir: "ltr" },
];

const T = {
  /* ─── MONGOLIAN ─────────────────────────────────────────── */
  mn: {
    nav_home: "Нүүр",
    nav_tours: "Тур Аялал",
    nav_destinations: "Газрууд",
    nav_itineraries: "Хөтөлбөрүүд",
    nav_services: "Үйлчилгээ",
    nav_contact: "Холбогдох",
    nav_login: "Нэвтрэх",
    nav_register: "Бүртгүүлэх",
    nav_signin: "Нэвтрэх",
    nav_profile: "Профайл",
    nav_bookings: "Захиалгууд",
    nav_admin: "Админ",
    nav_signout: "Гарах",
    hero_label: "Дэлхийг нээ",
    hero_title1: "Дэлхийг",
    hero_title2: "Өөрийнхөөрөө тэтгэ",
    hero_sub:
      "Таны мөрөөдөлд нийцсэн гайхамшигт аялалууд. Далайн эрэгнээс түүхэн хотууд хүртэл — адал явдал хүлээж байна.",
    search_dest: "Байршил",
    search_dest_ph: "Хаана явах вэ?",
    search_date: "Огноо",
    search_guests: "Зочид",
    search_guests_ph: "Хэдэн хүн?",
    search_btn: "Хайх",
    stat_travelers: "Аялагч",
    stat_destinations: "Газар",
    stat_experience: "Жилийн туршлага",
    stat_rating: "Дундаж үнэлгээ",
    section_popular: "Алдартай",
    section_packages: "Онцлох Аялалууд",
    section_packages_sub: "Хамгийн их захиалагддаг аялалуудыг хар",
    section_dest: "Газрууд",
    section_dest_title: "Цэнхэр Газрууд",
    section_dest_sub: "Дэлхийн гайхамшигт газруудыг нээ",
    section_why: "Яагаад бидэн рүү хандах вэ?",
    section_why_sub: "Бид таны аяллыг онцгой болгохын төлөө хичээдэг",
    section_testimonials: "Аялагчдын сэтгэгдэл",
    section_newsletter: "Мэдэгдэл Авах",
    section_newsletter_sub:
      "Шинэ аялал, хямдралын мэдээллийг анхны хүний нэг болж аваарай",
    newsletter_ph: "Имэйл хаяг",
    newsletter_btn: "Бүртгүүлэх",
    newsletter_success: "🎉 Мэдэгдэл бүртгэгдлээ!",
    btn_book_now: "Одоо захиалах",
    btn_view_all: "Бүгдийг харах",
    btn_explore: "Судлах",
    btn_view_details: "Дэлгэрэнгүй",
    btn_book_tour: "Тур захиалах",
    btn_learn_more: "Дэлгэрэнгүй",
    from_price: "хамгийн багадаа",
    per_person: "/хүн",
    btn_contact_us: "Холбогдох",
    why_safe: "Найдвартай & Даатгалтай",
    why_safe_desc:
      "Бүх аялалд аялалын даатгал болон 24/7 яаралтай тусламж орно.",
    why_price: "Хамгийн Хямд Үнийн Баталгаа",
    why_price_desc: "Илүү хямд гэвэл дур мэдэн хямдруулна.",
    why_support: "24/7 Дэмжлэг",
    why_support_desc:
      "Манай аялалын мэргэжилтнүүд цагийн дугуйд туслахад бэлэн.",
    why_custom: "Хувийн Хөтөлбөр",
    why_custom_desc: "Таны хүсэл, төсөвт тохирсон аялалын хөтөлбөр.",
    page_packages: "Аялалын Багцууд",
    page_packages_sub: "Аяллын бүх загварт зориулагдсан аялалууд",
    page_itineraries: "Аялалын Хөтөлбөрүүд",
    page_itin_sub: "Өдөр бүрийн хөтөлбөр — бүх дэлгэрэнгүй нь төлөвлөгдсөн",
    page_destinations: "Аялах Газрууд",
    page_dest_sub: "Дэлхийн шилдэг газруудыг нээ",
    page_services: "Манай Үйлчилгээнүүд",
    page_services_sub: "Аяллын бүх хэрэгцээнд нийцсэн үйлчилгээ",
    page_contact: "Холбогдох",
    page_contact_sub: "Та бидэнтэй холбогдоход бид нааштайгаар хариулна",
    filter_search_ph: "Байршил эсвэл нэрээр хайх...",
    filter_any_budget: "Ямар ч төсөв",
    filter_all_types: "Бүх төрөл",
    filter_under: "Хүртэл",
    filter_featured: "Онцлох",
    filter_price_low: "Үнэ: Доод → Дээд",
    filter_price_high: "Үнэ: Дээд → Доод",
    filter_top_rated: "Шилдэг Үнэлгээ",
    filter_btn: "Шүүх",
    results_found_pkg: "аялал олдлоо",
    no_packages: "Аялал олдсонгүй",
    no_packages_sub: "Шүүлт эсвэл хайлтаа өөрчилнэ үү.",
    clear_filters: "Шүүлт арилгах",
    contact_name: "Нэр",
    contact_email: "Имэйл",
    contact_subject: "Гарчиг",
    contact_message: "Мессеж",
    contact_send: "Мессеж илгээх",
    contact_sending: "Илгээж байна...",
    contact_success: "Мессеж илгээгдлээ! Удахгүй холбогдно.",
    contact_error: "Мессеж илгээхэд алдаа гарлаа.",
    contact_phone: "Утасны дугаар",
    contact_address: "Хаяг",
    contact_hours: "Ажлын цаг",
    auth_welcome: "Тавтай морил",
    auth_login_title: "Нэвтрэх",
    auth_signup_title: "Бүртгүүлэх",
    auth_password: "Нууц үг",
    auth_confirm_pw: "Нууц үг баталгаажуулах",
    auth_forgot_pw: "Нууц үг мартсан?",
    auth_no_account: "Бүртгэл байхгүй юу?",
    auth_have_account: "Бүртгэлтэй юу?",
    auth_login_btn: "Нэвтрэх",
    auth_signup_btn: "Бүртгүүлэх",
    auth_name: "Нэр",
    auth_or: "эсвэл",
    footer_tagline:
      "Дэлхий даяар гайхамшигт аяллыг бүтээдэг. Таны аяллын мөрөөдлийг бодит болгоё.",
    footer_explore: "Судлах",
    footer_popular: "Алдартай Газрууд",
    footer_contact: "Холбогдох",
    footer_rights: "Бүх эрх хуулиар хамгаалагдсан.",
    footer_privacy: "Нууцлалын бодлого",
    footer_terms: "Үйлчилгээний нөхцөл",
    footer_home: "Нүүр",
    footer_packages: "Аялалын Багцууд",
    footer_services: "Газрууд",
    footer_itineraries: "Хөтөлбөрүүд",
    footer_about: "Бидний тухай",
    footer_hours: "Да-Ба: 9:00 - 18:00",
    my_bookings: "Миний Захиалгууд",
    no_bookings: "Захиалга байхгүй",
    booking_id: "Захиалгын дугаар",
    booking_status: "Төлөв",
    booking_date: "Огноо",
    booking_total: "Нийт",
    my_profile: "Миний Профайл",
    edit_profile: "Профайл засах",
    save_changes: "Хадгалах",
    cancel: "Болих",
    change_password: "Нууц үг солих",
    loading: "Уншиж байна...",
    error_load: "Өгөгдөл ачаалахад алдаа гарлаа.",
    retry: "Дахин оролдох",
    days: "Өдөр",
    persons: "хүн",
    book_now: "Одоо захиалах",
    user_profile: "Профайл",
    user_bookings: "Захиалгууд",
    user_logout: "Гарах",
    nav_festivals: "Наадам & Баяр",
    nav_about_mongolia: "Монгол Тухай",
    nav_shop: "Дэлгүүр",
    section_festivals: "Соёл & Баяр ёслол",
    section_about_mongolia: "Монголыг нээ",
    page_festivals: "Монголын Баяр Наадам",
    page_festivals_sub: "Монгол хүмүүсийн уламжлалт баяр ёслолуудыг мэдэр",
    page_about_mongolia: "Монгол Тухай",
    page_about_mongolia_sub:
      "Мөнхийн хөх тэнгэр, нүүдэлчдийн өв уламжлал, зэрлэг байгаль",
    page_shop: "Itravelmongolia Дэлгүүр",
    home_slogan: "Монголыг мэдэр, Дэлхийг нээ",
    home_intro: "Эртний нүүдэлчдийн нутаг — аялагчдын зүрхэнд үлддэг газар.",
    booking_failed: "Захиалга амжилтгүй боллоо. Дахин оролдоно уу.",
    booking_submitted_title: "Захиалга амжилттай илгээгдлээ!",
    booking_submitted_for: "",
    booking_submitted_received: " захиалга хүлээн авлаа.",
    booking_submitted_review:
      " Манай баг удахгүй шалгаад баталгаажуулах и-мэйл илгээнэ.",
    booking_step_received: "Захиалга хүлээн авсан, шалгаж байна",
    booking_step_approved: "Админ батлаад төлбөрийн линк илгээнэ",
    booking_step_payment: "Аяллаа баталгаажуулахын тулд төлбөрөө хийнэ үү",
    booking_view_my_bookings: "Миний захиалгууд",
    booking_explore_more_tours: "Илүү олон аялал үзэх",
    booking_almost_there: "Бараг боллоо!",
    booking_title: "Аяллаа захиалах",
    booking_subtitle:
      "Багцаа сонгоод мэдээллээ бөглөнө үү — манай баг удахгүй баталгаажуулна.",
    booking_tour_package: "Аяллын багц",
    booking_loading_packages: "Багцууд ачаалж байна…",
    booking_travel_date: "Аяллын огноо",
    booking_select_date: "Огноо сонгох",
    booking_guests_label: "Зочдын тоо",
    booking_checking_availability: "Суудлын үлдэгдэл шалгаж байна…",
    booking_slot_full: "Энэ цаг дүүрсэн байна — өөр огноо эсвэл цаг сонгоно уу",
    booking_of: "нийт",
    booking_spots_available: "суудал байна",
    booking_up_to: "Нэг цагт хамгийн ихдээ",
    booking_guests_per_slot: "зочин",
    booking_select_datetime_hint:
      "бодит үлдэгдэл харахын тулд огноо, цаг сонгоно уу",
    booking_departure_time: "Хөдлөх цаг",
    booking_select_time_slot: "Цагийн сонголт хийнэ үү",
    booking_special_requests: "Тусгай хүсэлт",
    booking_optional: "заавал биш",
    booking_special_placeholder:
      "Хоолны дэглэм, хүртээмжийн хэрэгцээ, ой тэмдэглэлт өдөр…",
    booking_back: "Буцах",
    booking_confirming: "Баталгаажуулж байна…",
    booking_confirm_booking: "Захиалга баталгаажуулах",
    booking_price_per_person: "Нэг хүний үнэ",
    booking_guests_count: "зочин",
    admin_users_count_label: "хэрэглэгч",
    admin_users_admins_label: "админ",
    admin_users_search_placeholder: "Хэрэглэгчийг имэйлээр хайх",
    admin_users_search_admin_placeholder: "Админ хайх",
    admin_users_actions: "Үйлдэл",
    admin_users_role: "Эрх",
    admin_users_joined: "Бүртгүүлсэн",
    admin_users_no_users: "Хэрэглэгч олдсонгүй",
    admin_users_no_admins: "Админ олдсонгүй",
    admin_users_make_admin: "Админ болгох",
    admin_users_delete_user: "Хэрэглэгч устгах",
    admin_users_remove_admin: "Админ эрх буцаах",
    admin_users_enter_email: "Имэйл оруулна уу.",
    admin_users_promoted: "Хэрэглэгч админ боллоо.",
    admin_users_make_failed: "Админ болгох үед алдаа гарлаа.",
    admin_users_confirm_remove_admin: "Энэ имэйлээс админ эрх буцаах уу:",
    admin_users_removed_admin: "Админ эрх буцаалаа.",
    admin_users_remove_failed: "Админ эрх буцаах үед алдаа гарлаа.",
    admin_users_confirm_delete: "Энэ хэрэглэгчийг database-с устгах уу:",
    admin_users_deleted: "Хэрэглэгчийг database-с устгалаа.",
    admin_users_delete_failed: "Хэрэглэгч устгах үед алдаа гарлаа.",
    lightbox_close: "Хаах",
    comments_title: "Сэтгэгдлүүд",
    comment_placeholder: "Энэ зурган дээр сэтгэгдэл бичих...",
    comment_submit: "Илгээх",
    comment_posting: "Илгээж байна...",
    comment_empty: "Одоогоор сэтгэгдэл алга. Эхний сэтгэгдлийг үлдээгээрэй!",
    comment_login_prompt: "Сэтгэгдэл үлдээхийн тулд нэвтэрнэ үү.",
    comment_login_link: "Нэвтрэх",
    comment_delete: "Устгах",
    comment_delete_confirm: "Энэ сэтгэгдлийг устгах уу?",
  },

  /* ─── ENGLISH ───────────────────────────────────────────── */
  en: {
    nav_home: "Home",
    nav_tours: "Tours",
    nav_destinations: "Destinations",
    nav_itineraries: "Itineraries",
    nav_services: "Services",
    nav_contact: "Contact",
    nav_login: "Login",
    nav_register: "Register",
    nav_signin: "Sign In",
    nav_profile: "Profile",
    nav_bookings: "My Bookings",
    nav_admin: "Admin",
    nav_signout: "Sign Out",
    hero_label: "Discover The World",
    hero_title1: "Explore The World",
    hero_title2: "Your Way",
    hero_sub:
      "Unforgettable journeys tailored to your dreams. From tropical beaches to historic cities — adventure awaits.",
    search_dest: "Destination",
    search_dest_ph: "Where to?",
    search_date: "Travel Date",
    search_guests: "Guests",
    search_guests_ph: "How many?",
    search_btn: "Search",
    stat_travelers: "Happy Travelers",
    stat_destinations: "Destinations",
    stat_experience: "Years Experience",
    stat_rating: "Average Rating",
    section_popular: "Popular",
    section_packages: "Featured Packages",
    section_packages_sub: "Hand-picked tours loved by thousands of travelers",
    section_dest: "Destinations",
    section_dest_title: "Top Destinations",
    section_dest_sub: "Discover the world's most breathtaking locations",
    section_why: "Why Choose Us?",
    section_why_sub: "We go above and beyond to make your trip extraordinary",
    section_testimonials: "Traveler Reviews",
    section_newsletter: "Stay Updated",
    section_newsletter_sub:
      "Be the first to know about new tours and exclusive deals",
    newsletter_ph: "Your email address",
    newsletter_btn: "Subscribe",
    newsletter_success: "🎉 You're subscribed!",
    btn_book_now: "Book Now",
    btn_view_all: "View All",
    btn_explore: "Explore",
    btn_view_details: "View Details",
    btn_book_tour: "Book a Tour",
    btn_learn_more: "Learn More",
    from_price: "from",
    per_person: "/person",
    btn_contact_us: "Contact Us",
    why_safe: "Safe & Insured",
    why_safe_desc:
      "All trips include travel insurance and 24/7 emergency support.",
    why_price: "Best Price Guarantee",
    why_price_desc: "Find it cheaper and we'll beat any price, guaranteed.",
    why_support: "24/7 Support",
    why_support_desc: "Our travel experts are available around the clock.",
    why_custom: "Custom Itineraries",
    why_custom_desc:
      "Tailor-made travel plans built around your preferences and budget.",
    page_packages: "Tour Packages",
    page_packages_sub: "Handcrafted journeys for every kind of traveler",
    page_itineraries: "Itineraries",
    page_itin_sub: "Day-by-day travel plans — every moment planned",
    page_destinations: "Destinations",
    page_dest_sub: "Discover the world's finest destinations",
    page_services: "Our Services",
    page_services_sub: "Everything you need for the perfect trip",
    page_contact: "Contact Us",
    page_contact_sub: "We'd love to hear from you",
    filter_search_ph: "Search by destination or name...",
    filter_any_budget: "Any Budget",
    filter_all_types: "All Types",
    filter_under: "Under",
    filter_featured: "Featured",
    filter_price_low: "Price: Low → High",
    filter_price_high: "Price: High → Low",
    filter_top_rated: "Top Rated",
    filter_btn: "Filter",
    results_found_pkg: "packages found",
    no_packages: "No packages found",
    no_packages_sub: "Try adjusting your filters or search term.",
    clear_filters: "Clear Filters",
    contact_name: "Name",
    contact_email: "Email",
    contact_subject: "Subject",
    contact_message: "Message",
    contact_send: "Send Message",
    contact_sending: "Sending...",
    contact_success: "Message sent! We'll get back to you soon.",
    contact_error: "Failed to send message.",
    contact_phone: "Phone",
    contact_address: "Address",
    contact_hours: "Working Hours",
    auth_welcome: "Welcome",
    auth_login_title: "Sign In",
    auth_signup_title: "Create Account",
    auth_password: "Password",
    auth_confirm_pw: "Confirm Password",
    auth_forgot_pw: "Forgot Password?",
    auth_no_account: "Don't have an account?",
    auth_have_account: "Already have an account?",
    auth_login_btn: "Sign In",
    auth_signup_btn: "Create Account",
    auth_name: "Full Name",
    auth_or: "or",
    footer_tagline:
      "Crafting extraordinary journeys around the world. Let us turn your travel dreams into unforgettable memories.",
    footer_explore: "Explore",
    footer_popular: "Popular Destinations",
    footer_contact: "Contact Us",
    footer_rights: "All rights reserved.",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_home: "Home",
    footer_packages: "Tour Packages",
    footer_services: "Destinations",
    footer_itineraries: "Itineraries",
    footer_about: "About Us",
    footer_hours: "Mon–Fri: 9 AM – 6 PM",
    my_bookings: "My Bookings",
    no_bookings: "No bookings yet",
    booking_id: "Booking ID",
    booking_status: "Status",
    booking_date: "Date",
    booking_total: "Total",
    my_profile: "My Profile",
    edit_profile: "Edit Profile",
    save_changes: "Save Changes",
    cancel: "Cancel",
    change_password: "Change Password",
    loading: "Loading...",
    error_load: "Failed to load data.",
    retry: "Retry",
    days: "Days",
    persons: "persons",
    book_now: "Book Now",
    user_profile: "Profile",
    user_bookings: "My Bookings",
    user_logout: "Sign Out",
    nav_festivals: "Festivals",
    nav_about_mongolia: "About Mongolia",
    nav_shop: "Shop",
    section_festivals: "Culture & Celebration",
    section_about_mongolia: "Discover Mongolia",
    page_festivals: "Festivals of Mongolia",
    page_festivals_sub:
      "Experience the vibrant traditions and timeless celebrations of the Mongolian people",
    page_about_mongolia: "About Mongolia",
    page_about_mongolia_sub:
      "Land of eternal blue skies, nomadic heritage, and untamed wilderness",
    page_shop: "Itravelmongolia Shop",
    home_slogan: "Discover Mongolia, Explore the World",
    home_intro:
      "The land of ancient nomads — a place that stays forever in the hearts of travellers.",
    booking_failed: "Booking failed. Please try again.",
    booking_submitted_title: "Booking Submitted!",
    booking_submitted_for: "Your booking for ",
    booking_submitted_received: " has been received.",
    booking_submitted_review:
      " Our team will review it shortly and send you a confirmation email.",
    booking_step_received: "Booking received & under review",
    booking_step_approved: "Admin approves & sends payment link",
    booking_step_payment: "Complete payment to confirm your trip",
    booking_view_my_bookings: "View My Bookings",
    booking_explore_more_tours: "Explore More Tours",
    booking_almost_there: "Almost there!",
    booking_title: "Book Your Tour",
    booking_subtitle:
      "Select a package and fill in your details — our team will confirm shortly.",
    booking_tour_package: "Tour Package",
    booking_loading_packages: "Loading packages…",
    booking_travel_date: "Travel Date",
    booking_select_date: "Select a date",
    booking_guests_label: "Number of Guests",
    booking_checking_availability: "Checking availability…",
    booking_slot_full:
      "This slot is fully booked — choose another date or time",
    booking_of: "of",
    booking_spots_available: "spots available",
    booking_up_to: "Up to",
    booking_guests_per_slot: "guests per slot",
    booking_select_datetime_hint: "select date & time to see live availability",
    booking_departure_time: "Departure Time",
    booking_select_time_slot: "Please select a time slot",
    booking_special_requests: "Special Requests",
    booking_optional: "optional",
    booking_special_placeholder:
      "Dietary requirements, accessibility needs, anniversaries…",
    booking_back: "Back",
    booking_confirming: "Confirming…",
    booking_confirm_booking: "Confirm Booking",
    booking_price_per_person: "Price per person",
    booking_guests_count: "guests",
    admin_users_count_label: "users",
    admin_users_admins_label: "admins",
    admin_users_search_placeholder: "Search user by email",
    admin_users_search_admin_placeholder: "Search admin by email",
    admin_users_actions: "Actions",
    admin_users_role: "Role",
    admin_users_joined: "Joined",
    admin_users_no_users: "No users found",
    admin_users_no_admins: "No admins found",
    admin_users_make_admin: "Make Admin",
    admin_users_delete_user: "Delete User",
    admin_users_remove_admin: "Remove Admin",
    admin_users_enter_email: "Please enter an email.",
    admin_users_promoted: "User promoted to admin.",
    admin_users_make_failed: "Failed to make admin.",
    admin_users_confirm_remove_admin: "Remove admin role from",
    admin_users_removed_admin: "Admin role removed.",
    admin_users_remove_failed: "Failed to remove admin role.",
    admin_users_confirm_delete: "Delete this user from database",
    admin_users_deleted: "User deleted from database.",
    admin_users_delete_failed: "Failed to delete user.",
    lightbox_close: "Close",
    comments_title: "Comments",
    comment_placeholder: "Add a comment about this photo...",
    comment_submit: "Post",
    comment_posting: "Posting...",
    comment_empty: "No comments yet. Be the first to comment!",
    comment_login_prompt: "Please log in to leave a comment.",
    comment_login_link: "Log in",
    comment_delete: "Delete",
    comment_delete_confirm: "Delete this comment?",
  },

  /* ─── GERMAN ────────────────────────────────────────────── */
  de: {
    nav_home: "Startseite",
    nav_tours: "Touren",
    nav_destinations: "Reiseziele",
    nav_itineraries: "Reisepläne",
    nav_services: "Dienste",
    nav_contact: "Kontakt",
    nav_login: "Anmelden",
    nav_register: "Registrieren",
    nav_signin: "Einloggen",
    nav_profile: "Profil",
    nav_bookings: "Buchungen",
    nav_admin: "Admin",
    nav_signout: "Abmelden",
    hero_label: "Entdecke die Welt",
    hero_title1: "Die Welt Entdecken",
    hero_title2: "Auf deine Weise",
    hero_sub:
      "Unvergessliche Reisen nach deinen Wünschen. Von tropischen Stränden bis zu historischen Städten — das Abenteuer wartet.",
    search_dest: "Reiseziel",
    search_dest_ph: "Wohin geht die Reise?",
    search_date: "Reisedatum",
    search_guests: "Gäste",
    search_guests_ph: "Wie viele?",
    search_btn: "Suchen",
    stat_travelers: "Glückliche Reisende",
    stat_destinations: "Reiseziele",
    stat_experience: "Jahre Erfahrung",
    stat_rating: "Durchschnittsbewertung",
    section_popular: "Beliebt",
    section_packages: "Empfohlene Pakete",
    section_packages_sub:
      "Handverlesene Reisen, von tausenden Reisenden geliebt",
    section_dest: "Reiseziele",
    section_dest_title: "Topreiseziele",
    section_dest_sub: "Entdecke die schönsten Orte der Welt",
    section_why: "Warum wir?",
    section_why_sub:
      "Wir gehen über das Normale hinaus, um deine Reise außergewöhnlich zu machen",
    section_testimonials: "Reisebewertungen",
    section_newsletter: "Auf dem Laufenden bleiben",
    section_newsletter_sub:
      "Sei Erster bei neuen Touren und exklusiven Angeboten",
    newsletter_ph: "Deine E-Mail-Adresse",
    newsletter_btn: "Abonnieren",
    newsletter_success: "🎉 Erfolgreich abonniert!",
    btn_book_now: "Jetzt buchen",
    btn_view_all: "Alle anzeigen",
    btn_explore: "Entdecken",
    btn_view_details: "Details anzeigen",
    btn_book_tour: "Tour buchen",
    btn_learn_more: "Mehr erfahren",
    from_price: "ab",
    per_person: "/Person",
    btn_contact_us: "Kontaktiere uns",
    why_safe: "Sicher & Versichert",
    why_safe_desc:
      "Alle Reisen beinhalten Reiseversicherung und 24/7-Notfallunterstützung.",
    why_price: "Bestpreisgarantie",
    why_price_desc: "Finde es günstiger und wir unterbieten jeden Preis.",
    why_support: "24/7-Support",
    why_support_desc: "Unsere Reiseexperten sind rund um die Uhr für dich da.",
    why_custom: "Individuelle Reisepläne",
    why_custom_desc:
      "Maßgeschneiderte Reisepläne nach deinen Wünschen und Budget.",
    page_packages: "Reisepakete",
    page_packages_sub: "Handgefertigte Reisen für jeden Reisetyp",
    page_itineraries: "Reisepläne",
    page_itin_sub: "Tagesweise Reisepläne — jeder Moment geplant",
    page_destinations: "Reiseziele",
    page_dest_sub: "Entdecke die besten Reiseziele der Welt",
    page_services: "Unsere Dienste",
    page_services_sub: "Alles für die perfekte Reise",
    page_contact: "Kontakt",
    page_contact_sub: "Wir freuen uns, von dir zu hören",
    filter_search_ph: "Nach Ziel oder Name suchen...",
    filter_any_budget: "Beliebiges Budget",
    filter_all_types: "Alle Typen",
    filter_under: "Unter",
    filter_featured: "Empfohlen",
    filter_price_low: "Preis: Niedrig → Hoch",
    filter_price_high: "Preis: Hoch → Niedrig",
    filter_top_rated: "Top bewertet",
    filter_btn: "Filtern",
    results_found_pkg: "Pakete gefunden",
    no_packages: "Keine Pakete gefunden",
    no_packages_sub: "Versuche, deine Filter oder Suche anzupassen.",
    clear_filters: "Filter löschen",
    contact_name: "Name",
    contact_email: "E-Mail",
    contact_subject: "Betreff",
    contact_message: "Nachricht",
    contact_send: "Nachricht senden",
    contact_sending: "Wird gesendet...",
    contact_success: "Nachricht gesendet! Wir melden uns bald.",
    contact_error: "Nachricht konnte nicht gesendet werden.",
    contact_phone: "Telefon",
    contact_address: "Adresse",
    contact_hours: "Öffnungszeiten",
    auth_welcome: "Willkommen",
    auth_login_title: "Einloggen",
    auth_signup_title: "Konto erstellen",
    auth_password: "Passwort",
    auth_confirm_pw: "Passwort bestätigen",
    auth_forgot_pw: "Passwort vergessen?",
    auth_no_account: "Noch kein Konto?",
    auth_have_account: "Bereits ein Konto?",
    auth_login_btn: "Einloggen",
    auth_signup_btn: "Konto erstellen",
    auth_name: "Vollständiger Name",
    auth_or: "oder",
    footer_tagline:
      "Außergewöhnliche Reisen rund um die Welt. Wir machen deine Reiseträume wahr.",
    footer_explore: "Entdecken",
    footer_popular: "Beliebte Reiseziele",
    footer_contact: "Kontakt",
    footer_rights: "Alle Rechte vorbehalten.",
    footer_privacy: "Datenschutz",
    footer_terms: "Nutzungsbedingungen",
    footer_home: "Startseite",
    footer_packages: "Reisepakete",
    footer_services: "Reiseziele",
    footer_itineraries: "Reisepläne",
    footer_about: "Über uns",
    footer_hours: "Mo–Fr: 9–18 Uhr",
    my_bookings: "Meine Buchungen",
    no_bookings: "Keine Buchungen",
    booking_id: "Buchungsnummer",
    booking_status: "Status",
    booking_date: "Datum",
    booking_total: "Gesamt",
    my_profile: "Mein Profil",
    edit_profile: "Profil bearbeiten",
    save_changes: "Änderungen speichern",
    cancel: "Abbrechen",
    change_password: "Passwort ändern",
    loading: "Lädt...",
    error_load: "Fehler beim Laden.",
    retry: "Erneut versuchen",
    days: "Tage",
    persons: "Personen",
    book_now: "Jetzt buchen",
    user_profile: "Profil",
    user_bookings: "Buchungen",
    user_logout: "Abmelden",
    nav_festivals: "Festivals",
    nav_about_mongolia: "Über die Mongolei",
    nav_shop: "Shop",
    section_festivals: "Kultur & Feste",
    section_about_mongolia: "Die Mongolei entdecken",
    page_festivals: "Mongolische Feste",
    page_festivals_sub:
      "Erlebe die lebendigen Traditionen des mongolischen Volkes",
    page_about_mongolia: "Über die Mongolei",
    page_about_mongolia_sub:
      "Land des ewigen blauen Himmels, Nomadenerbe und unberührter Wildnis",
    page_shop: "Itravelmongolia Shop",
    home_slogan: "Die Mongolei entdecken, die Welt erkunden",
    home_intro:
      "Das Land der alten Nomaden — ein Ort, der für immer im Herzen bleibt.",
    booking_failed: "Buchung fehlgeschlagen. Bitte versuche es erneut.",
    booking_submitted_title: "Buchung gesendet!",
    booking_submitted_for: "Deine Buchung für ",
    booking_submitted_received: " wurde erhalten.",
    booking_submitted_review:
      " Unser Team prüft sie in Kürze und sendet dir eine Bestätigungs-E-Mail.",
    booking_step_received: "Buchung eingegangen & wird geprüft",
    booking_step_approved: "Admin genehmigt & sendet Zahlungslink",
    booking_step_payment: "Zahlung abschließen, um deine Reise zu bestätigen",
    booking_view_my_bookings: "Meine Buchungen ansehen",
    booking_explore_more_tours: "Weitere Touren entdecken",
    booking_almost_there: "Fast geschafft!",
    booking_title: "Buche deine Tour",
    booking_subtitle:
      "Wähle ein Paket und fülle deine Daten aus — unser Team bestätigt in Kürze.",
    booking_tour_package: "Tourpaket",
    booking_loading_packages: "Pakete werden geladen…",
    booking_travel_date: "Reisedatum",
    booking_select_date: "Datum auswählen",
    booking_guests_label: "Anzahl der Gäste",
    booking_checking_availability: "Verfügbarkeit wird geprüft…",
    booking_slot_full:
      "Dieser Slot ist ausgebucht — bitte anderes Datum oder Uhrzeit wählen",
    booking_of: "von",
    booking_spots_available: "Plätze verfügbar",
    booking_up_to: "Bis zu",
    booking_guests_per_slot: "Gäste pro Slot",
    booking_select_datetime_hint:
      "Datum & Uhrzeit wählen, um Live-Verfügbarkeit zu sehen",
    booking_departure_time: "Abfahrtszeit",
    booking_select_time_slot: "Bitte eine Uhrzeit auswählen",
    booking_special_requests: "Besondere Wünsche",
    booking_optional: "optional",
    booking_special_placeholder: "Ernährung, Barrierefreiheit, Jubiläen…",
    booking_back: "Zurück",
    booking_confirming: "Wird bestätigt…",
    booking_confirm_booking: "Buchung bestätigen",
    booking_price_per_person: "Preis pro Person",
    booking_guests_count: "Gäste",
    admin_users_count_label: "Benutzer",
    admin_users_admins_label: "Admins",
    admin_users_search_placeholder: "Benutzer nach E-Mail suchen",
    admin_users_search_admin_placeholder: "Admin suchen",
    admin_users_actions: "Aktionen",
    admin_users_role: "Rolle",
    admin_users_joined: "Beigetreten",
    admin_users_no_users: "Keine Benutzer gefunden",
    admin_users_no_admins: "Keine Admins gefunden",
    admin_users_make_admin: "Zum Admin machen",
    admin_users_delete_user: "Benutzer löschen",
    admin_users_remove_admin: "Admin entfernen",
    admin_users_enter_email: "Bitte geben Sie eine E-Mail-Adresse ein.",
    admin_users_promoted: "Benutzer zum Admin befördert.",
    admin_users_make_failed: "Zum Admin machen fehlgeschlagen.",
    admin_users_confirm_remove_admin: "Admin-Rolle entfernen von",
    admin_users_removed_admin: "Admin-Rolle entfernt.",
    admin_users_remove_failed: "Entfernen der Admin-Rolle fehlgeschlagen.",
    admin_users_confirm_delete: "Diesen Benutzer aus der Datenbank löschen",
    admin_users_deleted: "Benutzer aus der Datenbank gelöscht.",
    admin_users_delete_failed: "Löschen des Benutzers fehlgeschlagen.",
    lightbox_close: "Schließen",
    comments_title: "Kommentare",
    comment_placeholder: "Kommentar zu diesem Foto hinzufügen...",
    comment_submit: "Senden",
    comment_posting: "Wird gesendet...",
    comment_empty: "Noch keine Kommentare. Sei der Erste!",
    comment_login_prompt: "Bitte melden Sie sich an, um einen Kommentar zu hinterlassen.",
    comment_login_link: "Anmelden",
    comment_delete: "Löschen",
    comment_delete_confirm: "Diesen Kommentar löschen?",
  },

  /* ─── KOREAN ────────────────────────────────────────────── */
  ko: {
    nav_home: "홈",
    nav_tours: "투어",
    nav_destinations: "여행지",
    nav_itineraries: "여행 일정",
    nav_services: "서비스",
    nav_contact: "문의",
    nav_login: "로그인",
    nav_register: "회원가입",
    nav_signin: "로그인",
    nav_profile: "프로필",
    nav_bookings: "예약 내역",
    nav_admin: "관리자",
    nav_signout: "로그아웃",
    hero_label: "세계를 발견하세요",
    hero_title1: "세계를 탐험하세요",
    hero_title2: "당신만의 방식으로",
    hero_sub:
      "꿈에 맞는 잊을 수 없는 여행. 열대 해변부터 역사적인 도시까지 — 모험이 기다립니다.",
    search_dest: "여행지",
    search_dest_ph: "어디로 가실건가요?",
    search_date: "여행 날짜",
    search_guests: "인원",
    search_guests_ph: "몇 명인가요?",
    search_btn: "검색",
    stat_travelers: "행복한 여행자",
    stat_destinations: "여행지",
    stat_experience: "년 경험",
    stat_rating: "평균 평점",
    section_popular: "인기",
    section_packages: "추천 패키지",
    section_packages_sub: "수천 명의 여행자들이 사랑하는 여행",
    section_dest: "여행지",
    section_dest_title: "인기 여행지",
    section_dest_sub: "세계에서 가장 아름다운 장소를 발견하세요",
    section_why: "왜 저희를 선택해야 하나요?",
    section_why_sub: "특별한 여행을 만들기 위해 최선을 다합니다",
    section_testimonials: "여행자 후기",
    section_newsletter: "최신 정보 받기",
    section_newsletter_sub: "새로운 투어와 특별 혜택을 가장 먼저 알아보세요",
    newsletter_ph: "이메일 주소",
    newsletter_btn: "구독",
    newsletter_success: "🎉 구독 완료!",
    btn_book_now: "지금 예약",
    btn_view_all: "전체 보기",
    btn_explore: "탐험",
    btn_view_details: "자세히 보기",
    btn_book_tour: "투어 예약",
    btn_learn_more: "더 알아보기",
    from_price: "부터",
    per_person: "/인",
    btn_contact_us: "문의하기",
    why_safe: "안전 & 보험",
    why_safe_desc: "모든 여행에 여행 보험과 24/7 긴급 지원이 포함됩니다.",
    why_price: "최저가 보장",
    why_price_desc: "더 저렴한 곳을 찾으면 가격을 맞춰드립니다.",
    why_support: "24/7 지원",
    why_support_desc: "여행 전문가들이 24시간 도움을 드립니다.",
    why_custom: "맞춤 일정",
    why_custom_desc: "취향과 예산에 맞춘 맞춤형 여행 계획.",
    page_packages: "여행 패키지",
    page_packages_sub: "모든 여행자를 위한 여행",
    page_itineraries: "여행 일정",
    page_itin_sub: "하루하루 계획된 여행 일정",
    page_destinations: "여행지",
    page_dest_sub: "세계 최고의 여행지를 발견하세요",
    page_services: "서비스",
    page_services_sub: "완벽한 여행을 위한 모든 것",
    page_contact: "문의하기",
    page_contact_sub: "언제든지 연락해 주세요",
    filter_search_ph: "여행지 또는 이름으로 검색...",
    filter_any_budget: "모든 예산",
    filter_all_types: "모든 유형",
    filter_under: "이하",
    filter_featured: "추천",
    filter_price_low: "가격: 낮은 순",
    filter_price_high: "가격: 높은 순",
    filter_top_rated: "높은 평점",
    filter_btn: "필터",
    results_found_pkg: "패키지 찾음",
    no_packages: "패키지 없음",
    no_packages_sub: "필터 또는 검색어를 바꿔보세요.",
    clear_filters: "필터 초기화",
    contact_name: "이름",
    contact_email: "이메일",
    contact_subject: "제목",
    contact_message: "메시지",
    contact_send: "메시지 보내기",
    contact_sending: "전송 중...",
    contact_success: "메시지 전송 완료! 곧 연락드리겠습니다.",
    contact_error: "메시지 전송 실패.",
    contact_phone: "전화번호",
    contact_address: "주소",
    contact_hours: "영업시간",
    auth_welcome: "환영합니다",
    auth_login_title: "로그인",
    auth_signup_title: "계정 만들기",
    auth_password: "비밀번호",
    auth_confirm_pw: "비밀번호 확인",
    auth_forgot_pw: "비밀번호를 잊으셨나요?",
    auth_no_account: "계정이 없나요?",
    auth_have_account: "계정이 있나요?",
    auth_login_btn: "로그인",
    auth_signup_btn: "계정 만들기",
    auth_name: "이름",
    auth_or: "또는",
    footer_tagline:
      "세계 곳곳에 특별한 여행을 만들어 드립니다. 여행의 꿈을 현실로.",
    footer_explore: "탐험",
    footer_popular: "인기 여행지",
    footer_contact: "문의",
    footer_rights: "모든 권리 보유.",
    footer_privacy: "개인정보 처리방침",
    footer_terms: "이용약관",
    footer_home: "홈",
    footer_packages: "여행 패키지",
    footer_services: "여행지",
    footer_itineraries: "여행 일정",
    footer_about: "회사 소개",
    footer_hours: "월–금: 오전 9시–오후 6시",
    my_bookings: "예약 내역",
    no_bookings: "예약 없음",
    booking_id: "예약 번호",
    booking_status: "상태",
    booking_date: "날짜",
    booking_total: "합계",
    my_profile: "내 프로필",
    edit_profile: "프로필 편집",
    save_changes: "변경 저장",
    cancel: "취소",
    change_password: "비밀번호 변경",
    loading: "로딩 중...",
    error_load: "데이터 로드 실패.",
    retry: "다시 시도",
    days: "일",
    persons: "명",
    book_now: "지금 예약",
    user_profile: "프로필",
    user_bookings: "예약 내역",
    user_logout: "로그아웃",
    nav_festivals: "축제",
    nav_about_mongolia: "몽골 소개",
    nav_shop: "쇼핑",
    section_festivals: "문화 & 축제",
    section_about_mongolia: "몽골 발견",
    page_festivals: "몽골의 축제",
    page_festivals_sub: "몽골 사람들의 생생한 전통과 축제를 경험하세요",
    page_about_mongolia: "몽골 소개",
    page_about_mongolia_sub:
      "영원한 푸른 하늘, 유목 문화유산, 그리고 드넓은 자연",
    page_shop: "Itravelmongolia 쇼핑",
    home_slogan: "몽골을 발견하고 세계를 탐험하세요",
    home_intro: "고대 유목민의 땅 — 여행자의 마음속에 영원히 남는 곳.",
    booking_failed: "예약에 실패했습니다. 다시 시도해 주세요.",
    booking_submitted_title: "예약이 접수되었습니다!",
    booking_submitted_for: "",
    booking_submitted_received: " 예약이 접수되었습니다.",
    booking_submitted_review:
      " 저희 팀이 곧 검토 후 확인 이메일을 보내드립니다.",
    booking_step_received: "예약 접수 및 검토 중",
    booking_step_approved: "관리자 승인 후 결제 링크 발송",
    booking_step_payment: "여행 확정을 위해 결제를 완료하세요",
    booking_view_my_bookings: "내 예약 보기",
    booking_explore_more_tours: "더 많은 투어 보기",
    booking_almost_there: "거의 완료됐어요!",
    booking_title: "투어 예약하기",
    booking_subtitle:
      "패키지를 선택하고 정보를 입력해 주세요 — 곧 저희 팀이 확인해 드립니다.",
    booking_tour_package: "투어 패키지",
    booking_loading_packages: "패키지를 불러오는 중…",
    booking_travel_date: "여행 날짜",
    booking_select_date: "날짜 선택",
    booking_guests_label: "인원 수",
    booking_checking_availability: "가능 인원 확인 중…",
    booking_slot_full:
      "이 시간대는 마감되었습니다 — 다른 날짜나 시간을 선택해 주세요",
    booking_of: "/",
    booking_spots_available: "석 이용 가능",
    booking_up_to: "최대",
    booking_guests_per_slot: "명/시간대",
    booking_select_datetime_hint:
      "실시간 가능 인원을 보려면 날짜와 시간을 선택하세요",
    booking_departure_time: "출발 시간",
    booking_select_time_slot: "시간대를 선택해 주세요",
    booking_special_requests: "특별 요청사항",
    booking_optional: "선택",
    booking_special_placeholder: "식단, 접근성 요구사항, 기념일 등…",
    booking_back: "뒤로",
    booking_confirming: "확인 중…",
    booking_confirm_booking: "예약 확정",
    booking_price_per_person: "1인 가격",
    booking_guests_count: "명",
    admin_users_count_label: "사용자",
    admin_users_admins_label: "관리자",
    admin_users_search_placeholder: "이메일로 사용자 검색",
    admin_users_search_admin_placeholder: "관리자 검색",
    admin_users_actions: "작업",
    admin_users_role: "역할",
    admin_users_joined: "가입일",
    admin_users_no_users: "사용자를 찾을 수 없습니다",
    admin_users_no_admins: "관리자를 찾을 수 없습니다",
    admin_users_make_admin: "관리자로 지정",
    admin_users_delete_user: "사용자 삭제",
    admin_users_remove_admin: "관리자 권한 제거",
    admin_users_enter_email: "이메일을 입력해 주세요.",
    admin_users_promoted: "사용자가 관리자로 승격되었습니다.",
    admin_users_make_failed: "관리자 지정에 실패했습니다.",
    admin_users_confirm_remove_admin: "다음 이메일의 관리자 권한을 제거하시겠습니까:",
    admin_users_removed_admin: "관리자 권한이 제거되었습니다.",
    admin_users_remove_failed: "관리자 권한 제거에 실패했습니다.",
    admin_users_confirm_delete: "이 사용자를 데이터베이스에서 삭제하시겠습니까",
    admin_users_deleted: "사용자가 데이터베이스에서 삭제되었습니다.",
    admin_users_delete_failed: "사용자 삭제에 실패했습니다.",
    lightbox_close: "닫기",
    comments_title: "댓글",
    comment_placeholder: "이 사진에 댓글을 남겨보세요...",
    comment_submit: "게시",
    comment_posting: "게시 중...",
    comment_empty: "아직 댓글이 없습니다. 첫 댓글을 남겨보세요!",
    comment_login_prompt: "댓글을 남기려면 로그인하세요.",
    comment_login_link: "로그인",
    comment_delete: "삭제",
    comment_delete_confirm: "이 댓글을 삭제하시겠습니까?",
  },

  /* ─── JAPANESE ──────────────────────────────────────────── */
  ja: {
    nav_home: "ホーム",
    nav_tours: "ツアー",
    nav_destinations: "目的地",
    nav_itineraries: "旅行プラン",
    nav_services: "サービス",
    nav_contact: "お問い合わせ",
    nav_login: "ログイン",
    nav_register: "登録",
    nav_signin: "サインイン",
    nav_profile: "プロフィール",
    nav_bookings: "予約一覧",
    nav_admin: "管理者",
    nav_signout: "サインアウト",
    hero_label: "世界を発見しよう",
    hero_title1: "世界を旅しよう",
    hero_title2: "自分のスタイルで",
    hero_sub:
      "夢に合わせた忘れられない旅。熱帯のビーチから歴史的な都市まで — 冒険があなたを待っています。",
    search_dest: "目的地",
    search_dest_ph: "どこへ行きますか？",
    search_date: "旅行日",
    search_guests: "ゲスト",
    search_guests_ph: "何名様？",
    search_btn: "検索",
    stat_travelers: "旅行者",
    stat_destinations: "目的地",
    stat_experience: "年の経験",
    stat_rating: "平均評価",
    section_popular: "人気",
    section_packages: "おすすめパッケージ",
    section_packages_sub: "多くの旅行者に愛される厳選ツアー",
    section_dest: "目的地",
    section_dest_title: "人気の目的地",
    section_dest_sub: "世界で最も美しい場所を発見しよう",
    section_why: "なぜ私たちを選ぶの？",
    section_why_sub: "あなたの旅を特別なものにするために全力を尽くします",
    section_testimonials: "旅行者のレビュー",
    section_newsletter: "最新情報を受け取る",
    section_newsletter_sub:
      "新しいツアーや特別なお得情報をいち早くお届けします",
    newsletter_ph: "メールアドレス",
    newsletter_btn: "登録",
    newsletter_success: "🎉 登録完了！",
    btn_book_now: "今すぐ予約",
    btn_view_all: "すべて見る",
    btn_explore: "探索",
    btn_view_details: "詳細を見る",
    btn_book_tour: "ツアーを予約",
    btn_learn_more: "もっと見る",
    from_price: "〜から",
    per_person: "/人",
    btn_contact_us: "お問い合わせ",
    why_safe: "安全・保険付き",
    why_safe_desc: "すべての旅行に旅行保険と24時間緊急サポートが含まれます。",
    why_price: "最低価格保証",
    why_price_desc: "安い価格を見つけたら必ず対応します。",
    why_support: "24時間サポート",
    why_support_desc: "旅行の専門家が24時間お手伝いします。",
    why_custom: "カスタム旅行プラン",
    why_custom_desc: "あなたの希望と予算に合わせたオーダーメイドの旅行プラン。",
    page_packages: "旅行パッケージ",
    page_packages_sub: "すべての旅行者向けに手作りされた旅",
    page_itineraries: "旅行プラン",
    page_itin_sub: "1日ごとに計画された旅行プラン",
    page_destinations: "目的地",
    page_dest_sub: "世界最高の目的地を発見しよう",
    page_services: "サービス",
    page_services_sub: "完璧な旅のためのすべて",
    page_contact: "お問い合わせ",
    page_contact_sub: "いつでもご連絡ください",
    filter_search_ph: "目的地または名前で検索...",
    filter_any_budget: "予算問わず",
    filter_all_types: "すべてのタイプ",
    filter_under: "以下",
    filter_featured: "おすすめ",
    filter_price_low: "価格: 安い順",
    filter_price_high: "価格: 高い順",
    filter_top_rated: "高評価",
    filter_btn: "フィルター",
    results_found_pkg: "パッケージ見つかりました",
    no_packages: "パッケージなし",
    no_packages_sub: "フィルターや検索語を変えてみてください。",
    clear_filters: "フィルタークリア",
    contact_name: "名前",
    contact_email: "メール",
    contact_subject: "件名",
    contact_message: "メッセージ",
    contact_send: "メッセージを送る",
    contact_sending: "送信中...",
    contact_success: "メッセージを送信しました！",
    contact_error: "送信に失敗しました。",
    contact_phone: "電話番号",
    contact_address: "住所",
    contact_hours: "営業時間",
    auth_welcome: "ようこそ",
    auth_login_title: "ログイン",
    auth_signup_title: "アカウント作成",
    auth_password: "パスワード",
    auth_confirm_pw: "パスワード確認",
    auth_forgot_pw: "パスワードをお忘れですか？",
    auth_no_account: "アカウントをお持ちでないですか？",
    auth_have_account: "すでにアカウントをお持ちですか？",
    auth_login_btn: "ログイン",
    auth_signup_btn: "アカウント作成",
    auth_name: "氏名",
    auth_or: "または",
    footer_tagline:
      "世界中で素晴らしい旅を提供しています。あなたの夢の旅を実現しましょう。",
    footer_explore: "探索",
    footer_popular: "人気の目的地",
    footer_contact: "お問い合わせ",
    footer_rights: "全著作権所有。",
    footer_privacy: "プライバシーポリシー",
    footer_terms: "利用規約",
    footer_home: "ホーム",
    footer_packages: "旅行パッケージ",
    footer_services: "目的地",
    footer_itineraries: "旅行プラン",
    footer_about: "会社概要",
    footer_hours: "月〜金: 9時〜18時",
    my_bookings: "予約一覧",
    no_bookings: "予約なし",
    booking_id: "予約番号",
    booking_status: "ステータス",
    booking_date: "日付",
    booking_total: "合計",
    my_profile: "マイプロフィール",
    edit_profile: "プロフィール編集",
    save_changes: "変更を保存",
    cancel: "キャンセル",
    change_password: "パスワード変更",
    loading: "読み込み中...",
    error_load: "データの読み込みに失敗しました。",
    retry: "再試行",
    days: "日",
    persons: "名",
    book_now: "今すぐ予約",
    user_profile: "プロフィール",
    user_bookings: "予約一覧",
    user_logout: "サインアウト",
    nav_festivals: "フェスティバル",
    nav_about_mongolia: "モンゴルについて",
    nav_shop: "ショップ",
    section_festivals: "文化とお祝い",
    section_about_mongolia: "モンゴルを発見",
    page_festivals: "モンゴルのフェスティバル",
    page_festivals_sub: "モンゴルの人々の伝統と祭りを体験しよう",
    page_about_mongolia: "モンゴルについて",
    page_about_mongolia_sub:
      "永遠の青い空、遊牧民の遺産、そして手つかずの大自然",
    page_shop: "Itravelmongolia ショップ",
    home_slogan: "モンゴルを発見し、世界を旅しよう",
    home_intro: "古代遊牧民の地 — 旅人の心に永遠に残る場所。",
    booking_failed: "予約に失敗しました。もう一度お試しください。",
    booking_submitted_title: "予約を受け付けました！",
    booking_submitted_for: "",
    booking_submitted_received: " の予約を受け付けました。",
    booking_submitted_review: " 内容を確認後、確認メールをお送りします。",
    booking_step_received: "予約受付・確認中",
    booking_step_approved: "管理者が承認し、支払いリンクを送信",
    booking_step_payment: "お支払い完了で旅行が確定します",
    booking_view_my_bookings: "予約一覧を見る",
    booking_explore_more_tours: "他のツアーを見る",
    booking_almost_there: "もう少しです！",
    booking_title: "ツアー予約",
    booking_subtitle:
      "パッケージを選択して情報を入力してください。まもなく担当者が確認します。",
    booking_tour_package: "ツアーパッケージ",
    booking_loading_packages: "パッケージを読み込み中…",
    booking_travel_date: "旅行日",
    booking_select_date: "日付を選択",
    booking_guests_label: "人数",
    booking_checking_availability: "空き状況を確認中…",
    booking_slot_full:
      "この枠は満席です — 別の日付または時間を選択してください",
    booking_of: " / ",
    booking_spots_available: "席が利用可能",
    booking_up_to: "最大",
    booking_guests_per_slot: "名/枠",
    booking_select_datetime_hint:
      "リアルタイム空き状況を見るには日付と時間を選択してください",
    booking_departure_time: "出発時間",
    booking_select_time_slot: "時間枠を選択してください",
    booking_special_requests: "特別リクエスト",
    booking_optional: "任意",
    booking_special_placeholder: "食事制限、アクセシビリティ、記念日など…",
    booking_back: "戻る",
    booking_confirming: "確認中…",
    booking_confirm_booking: "予約を確定",
    booking_price_per_person: "1名あたりの料金",
    booking_guests_count: "名",
    admin_users_count_label: "ユーザー",
    admin_users_admins_label: "管理者",
    admin_users_search_placeholder: "メールでユーザーを検索",
    admin_users_search_admin_placeholder: "管理者を検索",
    admin_users_actions: "操作",
    admin_users_role: "権限",
    admin_users_joined: "登録日",
    admin_users_no_users: "ユーザーが見つかりません",
    admin_users_no_admins: "管理者が見つかりません",
    admin_users_make_admin: "管理者にする",
    admin_users_delete_user: "ユーザーを削除",
    admin_users_remove_admin: "管理者権限を削除",
    admin_users_enter_email: "メールアドレスを入力してください。",
    admin_users_promoted: "ユーザーを管理者に昇格しました。",
    admin_users_make_failed: "管理者への設定に失敗しました。",
    admin_users_confirm_remove_admin: "このメールの管理者権限を削除しますか:",
    admin_users_removed_admin: "管理者権限を削除しました。",
    admin_users_remove_failed: "管理者権限の削除に失敗しました。",
    admin_users_confirm_delete: "このユーザーをデータベースから削除しますか",
    admin_users_deleted: "ユーザーをデータベースから削除しました。",
    admin_users_delete_failed: "ユーザーの削除に失敗しました。",
    lightbox_close: "閉じる",
    comments_title: "コメント",
    comment_placeholder: "この写真にコメントを追加...",
    comment_submit: "投稿",
    comment_posting: "投稿中...",
    comment_empty: "まだコメントがありません。最初のコメントを残しましょう!",
    comment_login_prompt: "コメントを残すにはログインしてください。",
    comment_login_link: "ログイン",
    comment_delete: "削除",
    comment_delete_confirm: "このコメントを削除しますか?",
  },

  /* ─── CHINESE ───────────────────────────────────────────── */
  zh: {
    nav_home: "首页",
    nav_tours: "旅游",
    nav_destinations: "目的地",
    nav_itineraries: "行程",
    nav_services: "服务",
    nav_contact: "联系我们",
    nav_login: "登录",
    nav_register: "注册",
    nav_signin: "登录",
    nav_profile: "个人资料",
    nav_bookings: "我的预订",
    nav_admin: "管理员",
    nav_signout: "退出",
    hero_label: "探索世界",
    hero_title1: "探索世界",
    hero_title2: "属于你的方式",
    hero_sub:
      "为你的梦想量身打造难忘的旅程。从热带海滩到历史名城 — 冒险等待着你。",
    search_dest: "目的地",
    search_dest_ph: "去哪里？",
    search_date: "出行日期",
    search_guests: "旅客",
    search_guests_ph: "几位？",
    search_btn: "搜索",
    stat_travelers: "快乐旅行者",
    stat_destinations: "目的地",
    stat_experience: "年经验",
    stat_rating: "平均评分",
    section_popular: "热门",
    section_packages: "精选套餐",
    section_packages_sub: "数千旅行者喜爱的精选旅游",
    section_dest: "目的地",
    section_dest_title: "热门目的地",
    section_dest_sub: "发现世界上最美丽的地方",
    section_why: "为什么选择我们？",
    section_why_sub: "我们全力以赴让您的旅行与众不同",
    section_testimonials: "旅行者评价",
    section_newsletter: "获取最新资讯",
    section_newsletter_sub: "第一时间了解新旅游和独家优惠",
    newsletter_ph: "电子邮件地址",
    newsletter_btn: "订阅",
    newsletter_success: "🎉 订阅成功！",
    btn_book_now: "立即预订",
    btn_view_all: "查看全部",
    btn_explore: "探索",
    btn_view_details: "查看详情",
    btn_book_tour: "预订旅游",
    btn_learn_more: "了解更多",
    from_price: "起",
    per_person: "/人",
    btn_contact_us: "联系我们",
    why_safe: "安全有保障",
    why_safe_desc: "所有旅行均包含旅游保险和24/7紧急支援。",
    why_price: "最低价格保证",
    why_price_desc: "找到更低价格，我们一定匹配。",
    why_support: "24/7支持",
    why_support_desc: "我们的旅行专家全天候为您提供帮助。",
    why_custom: "定制行程",
    why_custom_desc: "根据您的喜好和预算量身定制旅行计划。",
    page_packages: "旅游套餐",
    page_packages_sub: "为每类旅行者精心打造的旅程",
    page_itineraries: "旅行行程",
    page_itin_sub: "逐日规划的旅行方案",
    page_destinations: "目的地",
    page_dest_sub: "发现世界最佳目的地",
    page_services: "我们的服务",
    page_services_sub: "完美旅行所需的一切",
    page_contact: "联系我们",
    page_contact_sub: "随时欢迎您与我们联系",
    filter_search_ph: "按目的地或名称搜索...",
    filter_any_budget: "不限预算",
    filter_all_types: "所有类型",
    filter_under: "低于",
    filter_featured: "推荐",
    filter_price_low: "价格：低到高",
    filter_price_high: "价格：高到低",
    filter_top_rated: "评分最高",
    filter_btn: "筛选",
    results_found_pkg: "个套餐",
    no_packages: "未找到套餐",
    no_packages_sub: "请尝试调整筛选条件或搜索词。",
    clear_filters: "清除筛选",
    contact_name: "姓名",
    contact_email: "电子邮件",
    contact_subject: "主题",
    contact_message: "留言",
    contact_send: "发送消息",
    contact_sending: "发送中...",
    contact_success: "消息已发送！我们会尽快回复。",
    contact_error: "发送消息失败。",
    contact_phone: "电话",
    contact_address: "地址",
    contact_hours: "工作时间",
    auth_welcome: "欢迎",
    auth_login_title: "登录",
    auth_signup_title: "注册账户",
    auth_password: "密码",
    auth_confirm_pw: "确认密码",
    auth_forgot_pw: "忘记密码？",
    auth_no_account: "没有账户？",
    auth_have_account: "已有账户？",
    auth_login_btn: "登录",
    auth_signup_btn: "注册",
    auth_name: "全名",
    auth_or: "或",
    footer_tagline:
      "为您打造世界各地的精彩旅程。让我们把您的旅行梦想变成现实。",
    footer_explore: "探索",
    footer_popular: "热门目的地",
    footer_contact: "联系我们",
    footer_rights: "版权所有。",
    footer_privacy: "隐私政策",
    footer_terms: "服务条款",
    footer_home: "首页",
    footer_packages: "旅游套餐",
    footer_services: "目的地",
    footer_itineraries: "旅行行程",
    footer_about: "关于我们",
    footer_hours: "周一至五: 9:00-18:00",
    my_bookings: "我的预订",
    no_bookings: "暂无预订",
    booking_id: "预订编号",
    booking_status: "状态",
    booking_date: "日期",
    booking_total: "合计",
    my_profile: "个人资料",
    edit_profile: "编辑资料",
    save_changes: "保存更改",
    cancel: "取消",
    change_password: "修改密码",
    loading: "加载中...",
    error_load: "加载数据失败。",
    retry: "重试",
    days: "天",
    persons: "人",
    book_now: "立即预订",
    user_profile: "个人资料",
    user_bookings: "我的预订",
    user_logout: "退出",
    nav_festivals: "节日",
    nav_about_mongolia: "关于蒙古",
    nav_shop: "商店",
    section_festivals: "文化与庆典",
    section_about_mongolia: "探索蒙古",
    page_festivals: "蒙古节日",
    page_festivals_sub: "体验蒙古人民充满活力的传统与庆典",
    page_about_mongolia: "关于蒙古",
    page_about_mongolia_sub: "永恒蓝天之地、游牧文化遗产与原始荒野",
    page_shop: "Itravelmongolia 商店",
    home_slogan: "发现蒙古，探索世界",
    home_intro: "古代游牧民的土地 — 永远留在旅行者心中的地方。",
    booking_failed: "预订失败。请重试。",
    booking_submitted_title: "预订已提交！",
    booking_submitted_for: "",
    booking_submitted_received: " 的预订已收到。",
    booking_submitted_review: " 我们将尽快审核并发送确认邮件。",
    booking_step_received: "预订已接收，正在审核",
    booking_step_approved: "管理员审核后发送付款链接",
    booking_step_payment: "完成付款以确认您的行程",
    booking_view_my_bookings: "查看我的预订",
    booking_explore_more_tours: "浏览更多线路",
    booking_almost_there: "快完成了！",
    booking_title: "预订您的行程",
    booking_subtitle: "请选择套餐并填写信息 — 我们的团队将尽快确认。",
    booking_tour_package: "旅游套餐",
    booking_loading_packages: "正在加载套餐…",
    booking_travel_date: "出行日期",
    booking_select_date: "选择日期",
    booking_guests_label: "旅客人数",
    booking_checking_availability: "正在检查余位…",
    booking_slot_full: "该时段已满 — 请选择其他日期或时间",
    booking_of: "共",
    booking_spots_available: "个名额可用",
    booking_up_to: "最多",
    booking_guests_per_slot: "人/时段",
    booking_select_datetime_hint: "请选择日期和时间以查看实时余位",
    booking_departure_time: "出发时间",
    booking_select_time_slot: "请选择一个时间段",
    booking_special_requests: "特殊需求",
    booking_optional: "可选",
    booking_special_placeholder: "饮食要求、无障碍需求、纪念日等…",
    booking_back: "返回",
    booking_confirming: "确认中…",
    booking_confirm_booking: "确认预订",
    booking_price_per_person: "每人价格",
    booking_guests_count: "人",
    admin_users_count_label: "用户",
    admin_users_admins_label: "管理员",
    admin_users_search_placeholder: "按邮箱搜索用户",
    admin_users_search_admin_placeholder: "搜索管理员",
    admin_users_actions: "操作",
    admin_users_role: "角色",
    admin_users_joined: "加入时间",
    admin_users_no_users: "未找到用户",
    admin_users_no_admins: "未找到管理员",
    admin_users_make_admin: "设为管理员",
    admin_users_delete_user: "删除用户",
    admin_users_remove_admin: "取消管理员",
    admin_users_enter_email: "请输入邮箱。",
    admin_users_promoted: "用户已升级为管理员。",
    admin_users_make_failed: "设为管理员失败。",
    admin_users_confirm_remove_admin: "确定要取消该邮箱的管理员权限吗:",
    admin_users_removed_admin: "管理员权限已取消。",
    admin_users_remove_failed: "取消管理员权限失败。",
    admin_users_confirm_delete: "确定要从数据库中删除该用户吗",
    admin_users_deleted: "用户已从数据库中删除。",
    admin_users_delete_failed: "删除用户失败。",
    lightbox_close: "关闭",
    comments_title: "评论",
    comment_placeholder: "对这张照片发表评论...",
    comment_submit: "发布",
    comment_posting: "发布中...",
    comment_empty: "暂无评论,来发表第一条评论吧!",
    comment_login_prompt: "请登录后发表评论。",
    comment_login_link: "登录",
    comment_delete: "删除",
    comment_delete_confirm: "确定删除此评论吗?",
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLang] = useState(
    () => localStorage.getItem("lang") || "en",
  );
  const [theme, setTheme] = useState(
    () => localStorage.getItem("theme") || "light",
  );

  useEffect(() => {
    const langObj = LANGUAGES.find((l) => l.code === language) || LANGUAGES[1];
    document.documentElement.setAttribute("data-theme", theme);
    document.documentElement.setAttribute("dir", langObj.dir);
    document.documentElement.setAttribute("lang", language);
    localStorage.setItem("theme", theme);
    localStorage.setItem("lang", language);
  }, [theme, language]);

  const t = (key) => T[language]?.[key] ?? T.en[key] ?? key;
  const toggleTheme = () => setTheme((p) => (p === "light" ? "dark" : "light"));
  const setLanguage = (code) => setLang(code);
  const toggleLanguage = (code) => setLang(code);

  return (
    <LanguageContext.Provider
      value={{ language, theme, t, toggleTheme, toggleLanguage, setLanguage }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
